import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma, TeamLedgerEntryStatus, TeamLedgerHandStatus, TeamLedgerParticipantRole, TeamLedgerParticipantStatus, TeamLedgerRoomStatus } from "@prisma/client";
import { PrismaService } from "../prisma/prisma.service";
import { CreateTeamLedgerRoomDto } from "./dto/create-team-ledger-room.dto";
import { JoinTeamLedgerRoomDto } from "./dto/join-team-ledger-room.dto";
import { SubmitEntryDto } from "./dto/submit-entry.dto";

@Injectable()
export class TeamLedgerService {
  constructor(private readonly prisma: PrismaService) {}
  async createRoom(userId:string,dto:CreateTeamLedgerRoomDto){const user=await this.prisma.user.findUnique({where:{id:userId}});return this.prisma.teamLedgerRoom.create({data:{roomCode:await this.generateUniqueRoomCode(),title:dto.title||`${user?.nickname||"玩家"}的线下牌局`,ownerUserId:userId,note:dto.note,participants:{create:{userId,displayName:user?.nickname||"房主",seatNo:1,role:TeamLedgerParticipantRole.OWNER}}},include:{participants:true}})}
  async getRoom(roomCode:string){const r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode},include:{participants:{orderBy:{seatNo:"asc"},include:{user:{select:{id:true,nickname:true,avatarUrl:true}}}},hands:{orderBy:{handNo:"asc"},include:{entries:{include:{participant:true}}}},settlements:true}});if(!r)throw new NotFoundException("团队记账房不存在");return r}
  async joinRoom(userId:string,roomCode:string,dto:JoinTeamLedgerRoomDto){const r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode},include:{participants:true}});if(!r)throw new NotFoundException("团队记账房不存在");if(r.status!==TeamLedgerRoomStatus.WAITING)throw new BadRequestException("记账已开始，无法加入");const old=r.participants.find(p=>p.userId===userId);if(old){if(old.status===TeamLedgerParticipantStatus.LEFT)await this.prisma.teamLedgerParticipant.update({where:{id:old.id},data:{status:TeamLedgerParticipantStatus.ACTIVE,leftAt:null}});return this.getRoom(roomCode)}const u=await this.prisma.user.findUnique({where:{id:userId}});await this.prisma.teamLedgerParticipant.create({data:{roomId:r.id,userId,displayName:dto.displayName||u?.nickname||"玩家",seatNo:Math.max(...r.participants.map(p=>p.seatNo),0)+1}});return this.getRoom(roomCode)}
  async addTempParticipant(userId:string,roomCode:string,displayName:string){const r=await this.owner(userId,roomCode);const ps=await this.prisma.teamLedgerParticipant.findMany({where:{roomId:r.id}});await this.prisma.teamLedgerParticipant.create({data:{roomId:r.id,displayName,seatNo:Math.max(...ps.map(p=>p.seatNo),0)+1}});return this.getRoom(roomCode)}
  async startRoom(userId:string,roomCode:string){const r=await this.owner(userId,roomCode);const ps=await this.prisma.teamLedgerParticipant.count({where:{roomId:r.id,status:TeamLedgerParticipantStatus.ACTIVE}});if(ps<2)throw new BadRequestException("至少需要2名参与者");await this.prisma.teamLedgerRoom.update({where:{id:r.id},data:{status:TeamLedgerRoomStatus.ACTIVE,currentHandNo:0,startedAt:new Date()}});return this.getRoom(roomCode)}
  async createNextHand(userId:string,roomCode:string){const r=await this.owner(userId,roomCode);if(r.status!==TeamLedgerRoomStatus.ACTIVE)throw new BadRequestException("记账房未在进行中");const last=await this.prisma.teamLedgerHand.findFirst({where:{roomId:r.id},orderBy:{handNo:"desc"}});if(last&&last.status!==TeamLedgerHandStatus.LOCKED)throw new BadRequestException("上一手牌尚未锁定");const n=r.currentHandNo+1;await this.prisma.$transaction([this.prisma.teamLedgerHand.create({data:{roomId:r.id,handNo:n}}),this.prisma.teamLedgerRoom.update({where:{id:r.id},data:{currentHandNo:n}})]);return this.getRoom(roomCode)}
  async submitEntry(userId:string,roomCode:string,handNo:number,dto:SubmitEntryDto){const {room,hand}=await this.roomHand(roomCode,handNo);if(hand.status===TeamLedgerHandStatus.LOCKED)throw new BadRequestException("该手牌已锁定");const p=room.participants.find(x=>x.userId===userId);if(!p)throw new ForbiddenException("你不是本房间参与者");await this.upsert(hand.id,p.id,dto);if(hand.status===TeamLedgerHandStatus.DISPUTED){await this.prisma.teamLedgerHand.update({where:{id:hand.id},data:{status:TeamLedgerHandStatus.OPEN}})}await this.autoPromote(hand.id,room.id);return this.getRoom(roomCode)}
  async submitEntryForTemp(userId:string,roomCode:string,handNo:number,participantId:string,dto:SubmitEntryDto){const {room,hand}=await this.roomHand(roomCode,handNo);if(room.ownerUserId!==userId)throw new ForbiddenException("只有房主可以代临时玩家填写");const p=room.participants.find(x=>x.id===participantId);if(!p)throw new NotFoundException("参与者不存在");if(p.userId)throw new ForbiddenException("不能代注册用户填写，只能代临时玩家填写");await this.upsert(hand.id,p.id,dto);return this.getRoom(roomCode)}
  async setBuyIn(userId:string,roomCode:string,buyInAmount:number){const r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode},include:{participants:true}});if(!r)throw new NotFoundException("团队记账房不存在");const p=r.participants.find(x=>x.userId===userId&&x.status===TeamLedgerParticipantStatus.ACTIVE);if(!p)throw new ForbiddenException("你不是本房间参与者");if(buyInAmount<0)throw new BadRequestException("带入金额不能为负数");await this.prisma.teamLedgerParticipant.update({where:{id:p.id},data:{buyInAmount:new Prisma.Decimal(buyInAmount)}});return this.getRoom(roomCode)}
  async setBuyInForTemp(userId:string,roomCode:string,participantId:string,buyInAmount:number){const r=await this.owner(userId,roomCode);const p=await this.prisma.teamLedgerParticipant.findFirst({where:{id:participantId,roomId:r.id}});if(!p)throw new NotFoundException("参与者不存在");if(p.userId)throw new ForbiddenException("不能代注册用户设置");await this.prisma.teamLedgerParticipant.update({where:{id:p.id},data:{buyInAmount:new Prisma.Decimal(buyInAmount)}});return this.getRoom(roomCode)}
  async getHandBalance(roomCode:string,handNo:number){const {room,hand}=await this.roomHand(roomCode,handNo);const ids=room.participants.filter(p=>p.status===TeamLedgerParticipantStatus.ACTIVE).map(p=>p.id);const submittedEntries=hand.entries.filter(e=>ids.includes(e.participantId)&&(e.status===TeamLedgerEntryStatus.SUBMITTED||e.status===TeamLedgerEntryStatus.CONFIRMED));const total=submittedEntries.reduce((s,e)=>s.plus(e.amount),new Prisma.Decimal(0));const allSubmitted=ids.every(id=>submittedEntries.some(e=>e.participantId===id));return{handNo,status:hand.status,total:total.toNumber(),isBalanced:total.equals(0),allSubmitted,submittedCount:submittedEntries.length,totalCount:ids.length,entries:hand.entries.map(e=>({participantId:e.participantId,amount:e.amount.toNumber(),status:e.status}))}}
  async requestConfirmHand(userId:string,roomCode:string,handNo:number){const r=await this.owner(userId,roomCode),b=await this.getHandBalance(roomCode,handNo);if(!b.isBalanced)throw new BadRequestException(`账目不平衡，合计为 ${b.total}，需调整为 0`);if(!b.allSubmitted)throw new BadRequestException("还有参与者未提交金额");const h=await this.prisma.teamLedgerHand.findUnique({where:{roomId_handNo:{roomId:r.id,handNo}}});if(!h)throw new NotFoundException("该手牌不存在");await this.prisma.teamLedgerHand.update({where:{id:h.id},data:{status:TeamLedgerHandStatus.CONFIRMING}});return this.getRoom(roomCode)}
  async confirmHandEntry(userId:string,roomCode:string,handNo:number){const {room,hand}=await this.roomHand(roomCode,handNo);if(hand.status!==TeamLedgerHandStatus.CONFIRMING)throw new BadRequestException("该手牌未进入确认阶段");const p=room.participants.find(x=>x.userId===userId);if(!p)throw new ForbiddenException("你不是本房间参与者");await this.prisma.teamLedgerEntry.updateMany({where:{handId:hand.id,participantId:p.id},data:{status:TeamLedgerEntryStatus.CONFIRMED}});await this.promoteLocked(hand.id,room.id);return this.getRoom(roomCode)}
  async disputeHandEntry(userId:string,roomCode:string,handNo:number,note?:string){const {room,hand}=await this.roomHand(roomCode,handNo);const p=room.participants.find(x=>x.userId===userId);if(!p)throw new ForbiddenException("你不是本房间参与者");await this.prisma.$transaction(async tx=>{await tx.teamLedgerEntry.updateMany({where:{handId:hand.id},data:{status:TeamLedgerEntryStatus.PENDING,disputeNote:null}});await tx.teamLedgerEntry.updateMany({where:{handId:hand.id,participantId:p.id},data:{status:TeamLedgerEntryStatus.DISPUTED,disputeNote:note||null}});await tx.teamLedgerHand.update({where:{id:hand.id},data:{status:TeamLedgerHandStatus.DISPUTED}})});return this.getRoom(roomCode)}
  async getSummary(roomCode:string){const r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode},include:{participants:{where:{status:TeamLedgerParticipantStatus.ACTIVE},orderBy:{seatNo:"asc"}},hands:{where:{status:TeamLedgerHandStatus.LOCKED},orderBy:{handNo:"asc"},include:{entries:true}}}});if(!r)throw new NotFoundException("团队记账房不存在");const totals:Record<string,number>={};r.participants.forEach(p=>totals[p.id]=0);const handDetails=r.hands.map(h=>{const entries:Record<string,number>={};r.participants.forEach(p=>{const e=h.entries.find(x=>x.participantId===p.id);entries[p.id]=e?.amount.toNumber()||0;totals[p.id]+=entries[p.id]});return{handNo:h.handNo,entries,lockedAt:h.lockedAt}});return{roomCode,status:r.status,currentHandNo:r.currentHandNo,participants:r.participants.map(p=>({id:p.id,displayName:p.displayName,userId:p.userId,buyInAmount:p.buyInAmount?.toNumber()||0,cumulativeNet:totals[p.id],finalAmount:(p.buyInAmount?.toNumber()||0)+totals[p.id]})),handDetails}}
  async generateSettlement(roomCode:string){const s=await this.getSummary(roomCode),r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode}});if(!r)throw new NotFoundException();await this.prisma.settlementSuggestion.deleteMany({where:{roomId:r.id}});const cs=s.participants.filter(p=>p.finalAmount>0).sort((a,b)=>b.finalAmount-a.finalAmount),ds=s.participants.filter(p=>p.finalAmount<0).sort((a,b)=>a.finalAmount-b.finalAmount),out:any[]=[];let i=0,j=0;while(i<ds.length&&j<cs.length){const amount=Math.min(-ds[i].finalAmount,cs[j].finalAmount);out.push(await this.prisma.settlementSuggestion.create({data:{roomId:r.id,fromUserId:ds[i].userId,fromName:ds[i].displayName,toUserId:cs[j].userId,toName:cs[j].displayName,amount}}));ds[i].finalAmount+=amount;cs[j].finalAmount-=amount;if(!ds[i].finalAmount)i++;if(!cs[j].finalAmount)j++}return out}
  async endRoom(userId:string,roomCode:string){const r=await this.owner(userId,roomCode);await this.prisma.teamLedgerRoom.update({where:{id:r.id},data:{status:TeamLedgerRoomStatus.FINISHED,endedAt:new Date()}});return this.getRoom(roomCode)}
  async closeRoom(roomCode:string){await this.prisma.teamLedgerRoom.update({where:{roomCode},data:{status:TeamLedgerRoomStatus.CLOSED}});return{roomCode,status:"CLOSED"}}
  private async owner(userId:string,roomCode:string){const r=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode}});if(!r)throw new NotFoundException("团队记账房不存在");if(r.ownerUserId!==userId)throw new ForbiddenException("只有房主可以操作");return r}
  private async roomHand(roomCode:string,handNo:number){const room=await this.prisma.teamLedgerRoom.findUnique({where:{roomCode},include:{participants:true,hands:{where:{handNo},include:{entries:true}}}});if(!room)throw new NotFoundException("团队记账房不存在");const hand=room.hands[0];if(!hand)throw new NotFoundException("该手牌不存在");return{room,hand}}
  private upsert(handId:string,participantId:string,dto:SubmitEntryDto){return this.prisma.teamLedgerEntry.upsert({where:{handId_participantId:{handId,participantId}},update:{amount:new Prisma.Decimal(dto.amount),status:TeamLedgerEntryStatus.SUBMITTED,disputeNote:dto.disputeNote||null},create:{handId,participantId,amount:new Prisma.Decimal(dto.amount),status:TeamLedgerEntryStatus.SUBMITTED}})}
  private async autoPromote(handId:string,roomId:string){const h=await this.prisma.teamLedgerHand.findUnique({where:{id:handId},include:{entries:true}}),ps=await this.prisma.teamLedgerParticipant.findMany({where:{roomId,status:TeamLedgerParticipantStatus.ACTIVE}});if(h&&h.status===TeamLedgerHandStatus.OPEN&&ps.every(p=>h.entries.some(e=>e.participantId===p.id&&e.status!==TeamLedgerEntryStatus.PENDING))&&h.entries.reduce((s,e)=>s.plus(e.amount),new Prisma.Decimal(0)).equals(0))await this.prisma.teamLedgerHand.update({where:{id:handId},data:{status:TeamLedgerHandStatus.CONFIRMING}})}
  private async promoteLocked(handId:string,roomId:string){const h=await this.prisma.teamLedgerHand.findUnique({where:{id:handId},include:{entries:true}}),ps=await this.prisma.teamLedgerParticipant.findMany({where:{roomId,status:TeamLedgerParticipantStatus.ACTIVE}});if(h&&ps.every(p=>h.entries.some(e=>e.participantId===p.id&&e.status===TeamLedgerEntryStatus.CONFIRMED)))await this.prisma.teamLedgerHand.update({where:{id:handId},data:{status:TeamLedgerHandStatus.LOCKED,lockedAt:new Date()}})}
  private async generateUniqueRoomCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";for(let n=0;n<20;n++){let c="";for(let i=0;i<6;i++)c+=chars[Math.floor(Math.random()*chars.length)];if(!await this.prisma.teamLedgerRoom.findUnique({where:{roomCode:c}}))return c}throw new BadRequestException("房间码生成失败")}
}
