import { api, ensureDevLogin } from "../../utils/request";
let timer:number|null=null;
Page({data:{mode:"",room:null as any,roomCodeInput:"",titleInput:"",tempNameInput:"",showCreateForm:false,showJoinForm:false,showTempPlayerForm:false,myWinEntry:"",myLossEntry:"",disputeNote:"",currentHand:null as any,isOwner:false,myParticipantId:"",summary:null as any,isBuyInPhase:false,allHaveBuyIn:false,myBuyIn:"",balance:null as any,settlements:[] as any[]},
onLoad(o:any){if(o.roomCode)this.setData({mode:"room",roomCodeInput:o.roomCode})},onShow(){this.loadData()},onUnload(){if(timer)clearInterval(timer)},
async loadData(){await ensureDevLogin();if(this.data.mode==="room"&&this.data.roomCodeInput)await this.refreshRoom()},
async refreshRoom(){try{const room=await api.get<any>(`/team-ledger/rooms/${this.data.roomCodeInput}`);const uid=(wx.getStorageSync("user")as any)?.id;const me=room.participants.find((p:any)=>p.userId===uid);const isBuyInPhase=room.status==="ACTIVE"&&room.currentHandNo===0;this.setData({room,currentHand:room.hands?.[room.hands.length-1]||null,isOwner:room.ownerUserId===uid,myParticipantId:me?.id||"",isBuyInPhase,allHaveBuyIn:room.participants.every((p:any)=>p.buyInAmount!==null&&p.buyInAmount!==undefined),myBuyIn:me?.buyInAmount===null||me?.buyInAmount===undefined?"":String(me.buyInAmount)});if(!timer)timer=setInterval(()=>this.refreshRoom(),2500)as any}catch(e:any){wx.showToast({title:e.message||"加载失败",icon:"none"})}},
toggleCreateForm(){this.setData({showCreateForm:!this.data.showCreateForm,showJoinForm:false})},toggleJoinForm(){this.setData({showJoinForm:!this.data.showJoinForm,showCreateForm:false})},toggleTempPlayerForm(){this.setData({showTempPlayerForm:!this.data.showTempPlayerForm})},
onTitleInput(e:any){this.setData({titleInput:e.detail.value})},onRoomCodeInput(e:any){this.setData({roomCodeInput:e.detail.value.toUpperCase()})},onTempNameInput(e:any){this.setData({tempNameInput:e.detail.value})},onWinInput(e:any){this.setData({myWinEntry:e.detail.value,myLossEntry:""})},onLossInput(e:any){this.setData({myLossEntry:e.detail.value,myWinEntry:""})},onDisputeNoteInput(e:any){this.setData({disputeNote:e.detail.value})},onBuyInInput(e:any){this.setData({myBuyIn:e.detail.value})},
async doCreateRoom(){const r=await api.post<any>("/team-ledger/rooms",{title:this.data.titleInput});this.setData({mode:"room",roomCodeInput:r.roomCode,showCreateForm:false});await this.refreshRoom()},
async doJoinRoom(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/join`,{});this.setData({mode:"room",showJoinForm:false});await this.refreshRoom()},
async addTempPlayer(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/add-temp`,{displayName:this.data.tempNameInput});this.setData({tempNameInput:"",showTempPlayerForm:false});await this.refreshRoom()},
async startRoom(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/start`,{});await this.refreshRoom()},async nextHand(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/next-hand`,{});await this.refreshRoom()},async setBuyIn(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/buy-in`,{buyInAmount:Number(this.data.myBuyIn)});await this.refreshRoom()},
async submitEntry(){const h=(this.data.currentHand as any);if(!h)return;const n=this.data.myWinEntry?Number(this.data.myWinEntry):-Number(this.data.myLossEntry);await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/hands/${h.handNo}/entry`,{amount:n});this.setData({myWinEntry:"",myLossEntry:""});await this.refreshRoom();await this.checkBalance()},
async checkBalance(){const h=this.data.currentHand as any;if(h)this.setData({balance:await api.get(`/team-ledger/rooms/${this.data.roomCodeInput}/hands/${h.handNo}/balance`)})},async requestConfirmation(){const h=this.data.currentHand as any;await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/hands/${h.handNo}/request-confirm`,{});await this.refreshRoom()},async confirmHand(){const h=this.data.currentHand as any;await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/hands/${h.handNo}/confirm`,{});await this.refreshRoom()},async disputeHand(){const h=this.data.currentHand as any;await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/hands/${h.handNo}/dispute`,{note:this.data.disputeNote});await this.refreshRoom()},
async loadSummary(){this.setData({summary:await api.get(`/team-ledger/rooms/${this.data.roomCodeInput}/summary`)})},async loadSettlement(){this.setData({settlements:await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/settlement`,{}) as any[]})},async endRoom(){await api.post(`/team-ledger/rooms/${this.data.roomCodeInput}/end`,{});await this.refreshRoom();await this.loadSummary()},leaveRoom(){if(timer){clearInterval(timer);timer=null}this.setData({mode:"",room:null,currentHand:null,summary:null})}
});
