export const ErrorCodes = {
  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_BANNED: 'AUTH_BANNED',
  AUTH_DEV_LOGIN_DISABLED: 'AUTH_DEV_LOGIN_DISABLED',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',

  // Game
  GAME_BUSY: 'GAME_BUSY',
  GAME_STATE_NOT_FOUND: 'GAME_STATE_NOT_FOUND',
  GAME_INVALID_ACTION: 'GAME_INVALID_ACTION',
  GAME_NOT_YOUR_TURN: 'GAME_NOT_YOUR_TURN',
  GAME_ROOM_CLOSED: 'GAME_ROOM_CLOSED',

  // Content & Security
  CONTENT_RISK_DETECTED: 'CONTENT_RISK_DETECTED',
  SECURITY_CHECK_FAILED: 'SECURITY_CHECK_FAILED',

  // Admin
  ADMIN_PERMISSION_DENIED: 'ADMIN_PERMISSION_DENIED',
  ADMIN_LAST_SUPER_ADMIN: 'ADMIN_LAST_SUPER_ADMIN',


  // System
  SYSTEM_CONFIG_INVALID: 'SYSTEM_CONFIG_INVALID',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
